# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Job1:
    # The type of runner that the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will 
    steps:
      - name: sleep for 5 secs
        run: sleep 60s
        shell: bash
      - name: print
        run: echo "thisis job 1"



  Job2:
    needs: Job1
    # The type of runner that the job
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 secs
        run: sleep 120s
        shell: bash
      - name: print
        run: echo "thisis job 2"

  Job3:
    needs: Job2
    # The type of runner that the job
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 3 secs
        run: sleep 180s
        shell: bash
      - name: print
        run: echo "thisis job 3"



      




      
