# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Job1:
    # The type of runner that the job
    runs-on: ubuntu-latest

    steps:
      - name: sleep for 5 secs
        run: sleep 4s
        shell: bash
      - name: checkout
        uses: actions/checkout@v4
      - name: print
        run: echo "thisis job 1"
      - name: Use local hello-world-action
        run: $GITHUB_WORKSPACE/workflows/hello.txt

